import companyLogoUrl from "../images/WFE_logo.png";

const FOOTER_TEXT = "Generated by WORKFORCEDGE HRMS";

let logoDataUrlPromise = null;
let tintedLogoDataUrlPromise = null;

const toDataUrl = async (assetUrl) => {
  const response = await fetch(assetUrl);
  if (!response.ok) {
    throw new Error("Failed to load logo asset");
  }

  const blob = await response.blob();
  return await new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
};

const getLogoDataUrl = async () => {
  if (!logoDataUrlPromise) {
    logoDataUrlPromise = toDataUrl(companyLogoUrl).catch(() => null);
  }
  return logoDataUrlPromise;
};

const tintLogoPurple = async (dataUrl) => {
  const image = await new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = reject;
    img.src = dataUrl;
  });

  const canvas = document.createElement("canvas");
  canvas.width = image.width;
  canvas.height = image.height;
  const ctx = canvas.getContext("2d");
  if (!ctx) return dataUrl;

  ctx.drawImage(image, 0, 0);
  const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);
  const data = imageData.data;

  const purple = { r: 139, g: 92, b: 246 };
  for (let i = 0; i < data.length; i += 4) {
    const alpha = data[i + 3];
    if (alpha === 0) continue;
    const luminance = (data[i] + data[i + 1] + data[i + 2]) / 765;
    const intensity = Math.max(0.55, luminance);
    data[i] = Math.min(255, Math.round(purple.r * intensity));
    data[i + 1] = Math.min(255, Math.round(purple.g * intensity));
    data[i + 2] = Math.min(255, Math.round(purple.b * intensity));
  }

  ctx.putImageData(imageData, 0, 0);
  return canvas.toDataURL("image/png");
};

const getTintedLogoDataUrl = async () => {
  if (!tintedLogoDataUrlPromise) {
    tintedLogoDataUrlPromise = (async () => {
      const logo = await getLogoDataUrl();
      if (!logo) return null;
      return await tintLogoPurple(logo);
    })().catch(() => null);
  }
  return tintedLogoDataUrlPromise;
};

export const addCorporatePdfHeader = async (
  doc,
  { title, subtitle, generatedAtLabel } = {},
) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const logoDataUrl = await getTintedLogoDataUrl();
  let y = 14;

  if (logoDataUrl) {
    // Render logo with preserved aspect ratio to avoid horizontal compression.
    const logoProps = doc.getImageProperties(logoDataUrl);
    const targetWidth = 44;
    const targetHeight = Math.max(10, Math.min(22, (targetWidth * logoProps.height) / logoProps.width));
    doc.addImage(logoDataUrl, "PNG", 14, y - 4, targetWidth, targetHeight);
  } else {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(26, 32, 44);
    doc.text("HR Report", 14, y + 5);
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(generatedAtLabel || `Generated: ${new Date().toLocaleString()}`, pageWidth - 14, y + 3, {
    align: "right",
  });

  y = 34;
  doc.setDrawColor(226, 232, 240);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;

  if (title) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(15, 23, 42);
    doc.text(title, 14, y);
    y += 7;
  }

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(71, 85, 105);
    doc.text(subtitle, 14, y);
    y += 6;
  }

  return y + 2;
};

export const addCorporatePdfFooters = (doc) => {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240);
    doc.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(FOOTER_TEXT, 14, pageHeight - 9);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 9, { align: "right" });
  }
};

export const escapeCsvValue = (value) => {
  const raw = value == null ? "" : String(value);
  if (/[",\n]/.test(raw)) {
    return `"${raw.replace(/"/g, '""')}"`;
  }
  return raw;
};
